slangs_dict = {

'bişi' : 'bir şey',
'bdk' : 'bir dakika',
'brz' : 'biraz',
'cnm' : 'canım',
'deil' : 'değil',
'dimi' : 'değil mi',
'dooru' : 'doğru',
'zmn' : 'zaman',
'yk' : 'yok',
'iilk' : 'iyilik',
'youn' : 'yoğun',
'bab' : 'baba',
'byes' : 'güle güle', 
'bradır' : 'kardeş',
'mrb' : 'merhaba',
'nbr' : 'ne haber',
'nys' : 'neyse',
'okl' : 'okul',
'oks' : 'tamam',
'pls' : 'lütfen',
'aney' : 'anne',
'alla' : 'allah',
'dio' : 'diyor',
'bakiim' : 'bakayım',
'diim' : 'diyeyim',
'duruoz' : 'duruyoruz',
'gidio' : 'gidiyor',
'gdio' : 'gidiyor',
'sie' : 'siktir git',
'siee' : 'siktir git',
'böle' : 'böyle', 
'fln' : 'falan',
'gbi' : 'gibi',
'hpsi' : 'hepsi',
'kdr' : 'kadar',
'süle' : 'söyle',
'öpt' : 'öptüm',
'olck' : 'olacak',
'oliim' : 'olayım',
'knuşmuo' : 'konuşmuyor',
'içiom' : 'içiyorum',
'içiorm' : 'içiyorum',
'gldm' : 'geldim',
'güssel' : 'güzel',
'güsel' : 'güzel',
'gzl' : 'güzel',
'öljem' : 'öleceğim',
'reca' : 'rica',
'saten' : 'zaten',
'böle' : 'böyle', 
'daa' : 'daha',
'hpsi' : 'hepsi',
'yni' : 'yani',
'bn' : 'ben',
'sn' : 'sen',
'saa' : 'sana',
'snle' : 'seninle', 
'snn' : 'senin',
'ewt' : 'evet',
'abv' : 'allah belanı versin',
'amk' : 'amına koyayım',
'aq' : 'amına koyayım',
'amq' : 'amına koyayım',
'sg' : 'siktir git',
'oç' : 'orospu çocuğu',
'nbr' : 'naber',
'slm' : 'selam',
'bb' : 'güle güle',
'grşz' : 'güle güle',
'grşrz' : 'güle güle',
'by' : 'güle güle',
'bye' : 'güle güle',
'muck' : 'öpüyorum',
'mujk' : 'öpüyorum',
'inş' : 'inşallah',
'mck' : 'öpüyorum',
'mcq' : 'öpüyorum',
'ajkm' : 'aşkım',
'acqhm' : 'aşkım',
'aşkm' : 'aşkım',
'kanki' : 'dostum',
'panpa' : 'dostum',
'gank' : 'dostum',
'aeo' : 'allaha emanet ol',
'öptm' : 'öpüyorum',
'kanki' : 'dostum',
'kankito' : 'dostum',
'olm' : 'oğlum',
'uln' : 'ulan',
'len' : 'ulan',
'ok' : 'tamam',
'oki' : 'tamam',
'oke' : 'tamam',
'tmm' : 'tamam',
'tm' : 'tamam',
'hg' : 'hoşgeldin',
'hb' : 'hoşbulduk',
'tnslm' : 'tanışalım',
'bgn' : 'bugün',
'yrn' : 'yarın',
'iiyim' : 'iyiyim',
'ii' : 'iyiyim',
'ıı' : 'iyiyim',
'saol' : 'sağol',
'cok ii' : 'çok iyi',
'walla' : 'valla',
'jnm' : 'canım',
'a.s' : 'aleyküm selam',
's.a' : 'selamun aleyküm',
'as' : 'aleyküm selam',
'sa' : 'selamun aleyküm',
'a.s.' : 'aleyküm selam',
's.a.' : 'selamun aleyküm',
'kib' : 'kendine iyi bak',
'aro' : 'allah razı olsun',
'blg' : 'bilginize',
'bilg' : 'bilginize',
'ds' : 'dikkatinize sunulur',
'hk' : 'hakkında',
'hn' : 'hanım',
'iç' : 'iyi çalışmalar',
'ing' : 'ingilizce',
'eng' : 'ingilizce',
'lcv' : 'lütfen cevap ver',
'ltf' : 'lütfen',
'svg' : 'sevgiler',
'syg' : 'saygılar',
'tşk' : 'teşekkürler',
'tsk' : 'teşekkürler',
'tbr' : 'tebrikler',
'nzm' : 'ne zaman',
'nslsn' : 'nasılsın',
'vs' : 'vesaire',

}
